name: Performance Regression Testing

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  k6_test:
    name: Run k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Указываем точную рабочую версию экшена от Grafana
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: test.js
